#official PostgreSQL image
FROM postgres:16

#Enviroment variables for the instalation 
ENV POSTGRES_DB=${DB_NAME} \
    POSTGRES_USER=${DB_USER} \
    POSTGRES_PASSWORD=${DB_PASSWORD}

# PORT that PostgreSQL port
EXPOSE 5432



