#official PostgreSQL image
FROM postgres::latest

#Enviroment variables for the instalation 
ENV POSTGRES_DB = DB_NAME \
    POSTGRES_USER = trance_and_dance \
    POSTGRES_PASSWORD = test 

# PORT that PostgreSQL port
EXPOSE 5432




