MAP_WIDTH: int = 25
MAP_HEIGHT: int = 10

PLAYER_HEIGHT: int = 3

PLAYER1_START_X: int = 1
PLAYER1_START_Y: int = MAP_HEIGHT // 2

PLAYER2_START_X: int = MAP_WIDTH - 2
PLAYER2_START_Y: int = MAP_HEIGHT // 2

BALL_START_X: int = MAP_WIDTH // 2
BALL_START_Y: int = MAP_HEIGHT // 2
BALL_START_DX: int = 1
BALL_START_DY: int = 1
